// Distortion Animation
export const logoTextPart = [
    {
        label:'D',
        textColor:0xffff0000
    },
    {
        label:'i',
        textColor:0xffff0000
    },
    {
        label:'s',
        textColor:0xffffffff
    },
    {
        label:'t',
        textColor:0xffffffff
    },
    {
        label:'o',
        textColor:0xffffffff
    },
    {
        label:'r',
        textColor:0xffffffff
    },
    {
        label:'t',
        textColor:0xffffffff
    },
    {
        label:'i',
        textColor:0xffffffff
    },
    {
        label:'o',
        textColor:0xffffffff
    },
    {
        label:'n',
        textColor:0xffffffff
    },
    {
        label:' A',
        textColor:0xffff0000
    },
    {
        label:'n',
        textColor:0xffff0000
    },
    {
        label:'i',
        textColor:0xffffffff
    },
    {
        label:'m',
        textColor:0xffffffff
    },
    {
        label:'a',
        textColor:0xffffffff
    },
    {
        label:'t',
        textColor:0xffffffff
    },
    {
        label:'i',
        textColor:0xffffffff
    },
    {
        label:'o',
        textColor:0xffffffff
    },
    {
        label:'n',
        textColor:0xffffffff
    }
    
]